name: APK Build Projesi
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Buildozer APK Hazirlama
        uses: ArtemSerebrennikov/buildozer-action@v1.2
        with:
          buildozer_version: master
          command: buildozer android debug

      - name: APK Dosyasini Disari Aktar
        uses: actions/upload-artifact@v3
        with:
          name: ip-takip-uygulamasi
          path: bin/*.apk
