name: APK Build Projesi
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Buildozer APK Hazirlama
        run: |
          sudo apt update
          sudo apt install -name build-essential git ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          sudo apt install -y libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev gcc g++ printf-dev libffi-dev libgdbm-dev libncursesw5-dev libreadline-gplv2-dev libncurses5-dev tk-dev
          pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.33
          buildozer android debug

      - name: APK Dosyasini Disari Aktar
        uses: actions/upload-artifact@v3
        with:
          name: ip-takip-uygulamasi
          path: bin/*.apk
